// <auto-generated />
namespace RollProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NameFixesAllItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameFixesAllItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202105110348425_NameFixes-AllItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
